### ISSUE TITLE
Compatibility issues with Sophisticated Storage Stack Upgrade

### ISSUE THREAD

**Issue by Ragneel92** [CyclopsMC/IntegratedCrafting#168]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

I'm currently playing the FTB NeoTech modpack. I've noticed that Integrated Crafting is giving me a message that there aren't enough ingredients in the storage. In this example, it needs 1010 redstone, but there are 8448 in the storage. After some research, I discovered that the problem is the Stack Upgrades for Sophisticated Storage. These upgrades combine the 8448 redstone into 5 stacks. Because of this, Integrated Crafting thinks that only 320 (5 * 64 redstone) are available. Would it be possible for Integrated Crafting to recognize the correct amount in the future without having to remove the Stack Upgrades?

<img width="625" height="292" alt="Image" src="https://github.com/user-attachments/assets/912d5a6d-d7f5-476e-9484-dce08972a5e8" />

<img width="681" height="207" alt="Image" src="https://github.com/user-attachments/assets/180ea8e4-d8c6-41b0-a08f-99fde791e133" />

Best regards

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Jack-McKalling** [comment]
I believe this might be a bug, in case how our mechanism for interpreting stack capacities is not (and should be) accounting for the stack upgrade. There was a change regarding this fairly recently.

But I'll await the dev for his call.

**Comment by rubensworks** [comment]
Are you sure you're using the latest ID mod versions?
This should have been fixed a long time ago already: https://github.com/CyclopsMC/IntegratedCrafting/issues/106

(also possibly related to https://github.com/CyclopsMC/IntegratedDynamics/issues/1558)

**Comment by Ragneel92** [comment]
I just double check it.
This should be the latest Versions of the Mods for Minecraft 1.20.4.
To be sour I downloaded them again and tested it.
Still the same result

IntegratedCrafting-1.20.4-neoforge-1.1.7
IntegratedDynamics-1.20.4-neoforge-1.21.8
IntegratedTerminals-1.20.4-neoforge-1.4.13
IntegratedTunnels-1.20.4-neoforge-1.8.26
sophisticatedstorage-1.20.4-0.10.24.802

**Comment by rubensworks** [comment]
> IntegratedCrafting-1.20.4

You seem to be using an unsupported MC version.
MC versions that are maintained are 1.19.2, 1.20.1, 1.21.1, and 1.21.8.
Updating to such a version will fix your problem.
